### ISSUE TITLE
Add authenticate user for dashboard 

### ISSUE THREAD

**Issue by jdcarey128** [Carbon-Knight/Front-End#20]
We can probably create a namespace for user and include the dashboard and all pages reached by user. We can then use a BaseController to define a before_action method to authenticate visitor is a current_user.

**Comment by JBelta** [comment]
As far as I know, we only have one kind of user. And we have a way to set current_user in our in our application_recored.rb. Would we need to do a name space, and should we include ourselves as users w/ the role of admin?

**Comment by ETBassist** [comment]
I guess there's some discussion to be had around what an admin role would have access to that's different from a regular user, but that's a solid idea. Possible extension?
